---

- name: Install git 
  yum: name=git state=present

- name: Install docker
  yum: name=docker state=present
  notify:
    - start docker service

- name: Make sure docker is running
  systemd: name=docker state=started enabled=yes

- name: Add ec2-user to docker group
  user: name=ec2-user groups=docker append=yes

- name: Install python2
  yum: name=python2-setuptools-38.4.0-3.amzn2.0.6.noarch state=present

- name: Install python3
  yum: name=python3-setuptools-38.4.0-3.amzn2.0.6.noarch state=present

- name: Install python2 pip
  yum: name=python2-pip-9.0.3-1.amzn2.0.1.noarch state=present

- name: Install python3 pip
  yum: name=python2-pip-9.0.3-1.amzn2.0.1.noarch state=present

- name: Install python docker module
  pip: name=docker state=present

#This is not the best practice, but only if you need to install and configure your credentils inside your instances
- name: Install AWS CLI
  pip: name=awscli state=latest

- name: Create the AWS config directory
  file:
    path=/home/ec2-user/.aws
    state=directory
    owner=ec2-user
    group=ec2-user
    mode=0755

- name: Copy AWS CLI config
  template:
    src=aws_cli_config.j2
    dest=/home/ec2-user/.aws/config
    owner=ec2-user
    group=ec2-user
    mode=0600

- name: Copy AWS CLI credentials
  template:
    src=aws_cli_credentials.j2
    dest=/home/ec2-user/.aws/credentials
    owner=ec2-user
    group=ec2-user
    mode=0600
